title: Briannah Barnett 
description: SNHU CS-499 Computer Science Capstone, ePortfolio
theme: jekyll-theme-merlot

# Optional social links shown by many themes
author: Briannah Barnett
github_username: Briannahrhea
